name: Sync Fork With Upstream

on:
  schedule:
    - cron: "*/10 * * * *"   # ogni 10 minuti
  workflow_dispatch:         # possibilità di lanciarlo a mano

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          ref: main           # cambia se il branch principale ha un altro nome

      - name: Sync with upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3
        with:
          upstream_repository: edoardoquerio-pixel/Materie
          upstream_branch: main          # branch sorgente (upstream)
          target_branch: main           # branch del tuo fork da aggiornare
          github_token: ${{ secrets.GITHUB_TOKEN }}
