name: Sync Fork With Upstream

on:
  schedule:
    - cron: "*/10 * * * *"   # ogni 10 minuti
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main   # cambia se il tuo branch principale ha un altro nome

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/edoardoquerio-pixel/Materie.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge upstream/main --no-edit || true

      - name: Push changes to fork
        run: |
          git push origin main
